### ISSUE TITLE
[Documentation] Improve documentation on how to implement

### ISSUE THREAD

**Issue by gavinangym** [microsoft/react-native-lazy-index#5]
Can we improve the documentation to have an example on how and where to implement, perhaps in the context of a standard react-native init app?

Currently the examples don't say where and how to implement in either the standard MainApplication.java or AppDelegate.m.

Also, on the js side, how/when do we call the load function?

**Comment by tido64** [comment]
Thanks for opening this issue. :heart:

Documentation is one of the many things we're working on, but feel free to open PRs if you have cycles to spare.

**Comment by gavinangym** [comment]
:-) I would help if I could, but don't know where to implement the code given in the example in a standard app

**Comment by tido64** [comment]
Typically, we would use this pattern in a brown field app where you have navigation going from a native-native view to a React Native one, and vice versa. You call `ReactExperienceLoader.load()` just before navigating to a React Native view so that the relevant JS bits will be loaded when actually needed rather than on app start.

If you’re already in JS, I think just using inline require should be enough. This module is about making it possible to have the same level of control on the native side.

**Comment by tido64** [comment]
Closing this as native changes are no longer necessary as of [2.0.0](https://github.com/microsoft/react-native-lazy-index/releases/tag/2.0.0). The JS side shouldn't require any changes to existing code either.
